name: Build and Deploy
env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.PROFILEO_TOKEN }} # This is automatically set by Github Actions
  USE_GITHUB_DATA: "true"
  #MEDIUM_USERNAME: "hash3liZer"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 1" # see https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # Build the Project
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token : ${{ secrets.PROFILEO_TOKEN }}
          branch: gh-pages 
          folder: build
          repository-name: 'hunter0x8/hunter0x8.github.io'
